### ISSUE TITLE
Erreur de base de donnée

### ISSUE THREAD

**Issue by ghost** [Gregory-Gerard/xdrop#4]
Bonjour, j'ai déployé xdrop sur mon PC Windows, avec MySQL. Malheureusement, une erreur 500 (Internal Server Error) est survenue. Je pense savoir d'où vient ce problème. J'ai créé une base de données appelée 'forge', cependant, l'erreur proviendrait du fait que les tables nécessaires au bon fonctionnement de l'application ne sont pas présentes. Auriez-vous une suggestion à me faire pour régler ce problème au plus vite ?

Avec mes remerciements,
ShadowMikado

**Comment by Gregory-Gerard** [comment]
Bonjour,

Les tables sont bien présentes dans ce projet, étant un projet Laravel, elles sont sous formes de migrations. Il suffit alors de lancer ces migrations pour avoir toutes les tables à jour sur votre base de données.

Vous trouverez la marche à suivre sur la documentation de Laravel : https://laravel.com/docs/10.x/migrations#running-migrations

Au besoin, n'hésitez pas si cela ne fonctionne toujours pas 😉

**Comment by ghost** [comment]
Bonjour,
Tout fonctionne correctement à présent, je vous remercie de votre aide.
